// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4242.RB_AAssistComm;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController armRollerVictor;
    public static DoubleSolenoid armArmSolenoid;
    public static SpeedController kickerVictor;
    public static DigitalInput kickerLimSwitch;
    public static SpeedController frontLeftMotor;
    public static SpeedController rearLeftMotor;
    public static SpeedController frontRightMotor;
    public static SpeedController rearRightMotor;
    public static RobotDrive drivetrain4;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        armRollerVictor = new Victor(6);
        LiveWindow.addActuator("Arm", "RollerVictor", (Victor) armRollerVictor);
        
        armArmSolenoid = new DoubleSolenoid(0,1);      
        LiveWindow.addActuator("Arm", "ArmSolenoid", armArmSolenoid);
        
        kickerVictor = new Victor(5);
        LiveWindow.addActuator("Kicker", "KickerVictor", (Victor) kickerVictor);
        
        kickerLimSwitch = new DigitalInput(1);
        LiveWindow.addSensor("Kicker", "KickerLimSwitch", kickerLimSwitch);
        
        frontLeftMotor = new Victor(0);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 1", (Victor) frontLeftMotor);
        
        rearLeftMotor = new Victor(1);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 2", (Victor) rearLeftMotor);
        
        frontRightMotor = new Victor(2);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 3", (Victor) frontRightMotor);
        
        rearRightMotor = new Victor(3);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 4", (Victor) rearRightMotor);
        
        drivetrain4 = new RobotDrive(frontLeftMotor, rearLeftMotor,
        		frontRightMotor, rearRightMotor);
        
        drivetrain4.setSafetyEnabled(false);
        drivetrain4.setExpiration(0.0);
        drivetrain4.setSensitivity(0.5);
        drivetrain4.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
