// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4242.RB_AAssistComm.subsystems;

import org.usfirst.frc4242.RB_AAssistComm.*;
import org.usfirst.frc4242.RB_AAssistComm.commands.ArcadeDrive;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drivetrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController speedController1 = RobotMap.frontLeftMotor;
    SpeedController speedController2 = RobotMap.rearLeftMotor;
    SpeedController speedController3 = RobotMap.frontRightMotor;
    SpeedController speedController4 = RobotMap.rearRightMotor;
    RobotDrive drivetrain = RobotMap.drivetrain4;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public void drive () {
    	
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void takeJoystickInputs(Joystick JS) {
    	drivetrain.arcadeDrive(JS);
    }
    
    public void stopDrive () {
    	drivetrain.drive(0,0);
    }
    
    public void autoDrive (double outputMagnitude, double curve) {
    	drivetrain.setSafetyEnabled(false);
    	drivetrain.drive(outputMagnitude, curve);
    }
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    	setDefaultCommand(new ArcadeDrive());
    }
}

