// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4242.RB_AAssistComm.subsystems;

import org.usfirst.frc4242.RB_AAssistComm.RobotMap;
import org.usfirst.frc4242.RB_AAssistComm.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Kicker extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController kickerVictor = RobotMap.kickerVictor;
    public DigitalInput kickerLimSwitch = RobotMap.kickerLimSwitch;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public void pullKickerDown () {
    	SmartDashboard.putBoolean("Kicker down", false);
    	while (!kickerLimSwitch.get()) {
    		kickerVictor.set(1);
    	}
    }
    
    public void fireTheKicker() {
    	kickerVictor.set(1);
    	Timer.delay(0.5);
    	SmartDashboard.putBoolean("Kicker down", false);
    }
    
    public void stopKicker() {
    	kickerVictor.set(0);
    	SmartDashboard.putBoolean("Kicker down", true);
    }
    
    public boolean kickerReady() {
    	SmartDashboard.putBoolean("Kicker down", true);
    	return kickerLimSwitch.get();
    }
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    	setDefaultCommand(new PullKicker());
    }
}

